AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  RFE Monthly sales report

  Sample SAM Template for sales-shipment-summary

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 900
    MemorySize: 526
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
Resources:
  SalesShipmentSummaryFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: rfe_monthly_sales_report/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: BUFFERED

      Environment:
        Variables:
          VINTRACE_KEY: "57e7d07e-9ee2-4ca9-b4d6-cbe53faad0ff"
          MPLCONFIGDIR: "/tmp"

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api

  SalesShipmentSummaryFunction:
    Description: Sales Shipment Summary Lambda Function ARN
    Value: !GetAtt SalesShipmentSummaryFunction.Arn
  SalesShipmentSummaryFunctionIamRole:
    Description: Implicit IAM Role created for Sales Shipment Summary function
    Value: !GetAtt SalesShipmentSummaryFunctionRole.Arn
